### ISSUE TITLE
setup.py:10 issue - can't get the version

### ISSUE THREAD

**Issue by stevejalim** [pcraciunoiu/django-nginx-memcache#1]
setup.py: 10: version = **import**('nginx_memcache').get_version()

results in 

 File "nginx_memcache/**init**.py", line 6, in get_version
        if VERSION[2]:
    IndexError: tuple index out of range
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/primarysite/.virtualenvs/primarysite/src/django-nginx-memcache/setup.py", line 10, in <module>

```
version = __import__('nginx_memcache').get_version()
```

  File "nginx_memcache/**init**.py", line 6, in get_version

```
if VERSION[2]:
```

IndexError: tuple index out of range

Is there a separate package that needs installing first? Looks a bit like this current code is expecting a previous version of the code to already be installed?

**Comment by stevejalim** [comment]
Actually, just patching this on my fork now - will submit a pull request
